name: C++ CI with Make

on:
  push:
    branches: [branchAutoPackage]
  pull_request:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ devscripts
          sudo apt-get install -y debhelper-compat=12

      - name: Configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      
      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc

      - name: Build
        run: make

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: funca-deb
          path: /home/runner/work/DevOps/funca_*.deb
          
