name: C++ CI with Make

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      
      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log
          
      - name: Install Dependencies
        uses: docker/setup-qemu-action@v3

      - name: Install Docker extensions
        uses: docker/setup-buildx-action@v1

      - name: Build ls
        run: docker buildx ls

      - name: DockerHub secrets data
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build and create Dockerfile image for amd64 version
        run: docker build --platform=linux/amd64 -t frodlik/optimaserver:amd64 --push .

      - name: Build and create Dockerfile image for arm64 version
        run: docker build --platform=linux/arm64 -t frodlik/optimaserver:arm64 --push .

      - name: Create manifest
        run: docker manifest create frodlik/optimaserver --amend frodlik/optimaserver:amd64 --amend frodlik/optimaserver:arm64

      - name: Push manifest to DockerHub
        run: docker manifest push frodlik/optimaserver

