name: C++ CI with Make

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      
      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log
