name: C++ CI with Make

on:
  push:
    branches: [branchMKR]
  pull_request:
    branches: [branchMKR]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Build Script
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++
          autoreconf --install
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List Docker Buildx Builders
        run: docker buildx ls

      - name: DockerHub Login
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image (amd64)
        run: docker build --platform=linux/amd64 -t frodlik/optimaserver:amd64 --push .

      - name: Build and Push Docker Image (arm64)
        run: docker build --platform=linux/arm64 -t frodlik/optimaserver:arm64 --push .

      - name: Create and Push Docker Manifest
        run: |
          docker manifest create frodlik/optimaserver --amend frodlik/optimaserver:amd64 --amend frodlik/optimaserver:arm64
          docker manifest push frodlik/optimaserver

